### ISSUE TITLE
Error: UMD and IIFE output formats are not supported for code-splitting builds.

### ISSUE THREAD

**Issue by csell5** [henriquehbr/svelte-typewriter#21]
@henriquehbr first awesome little library. Thank you.

I went to upgrade to the latest when I started getting the following error.

```
[!] Error: UMD and IIFE output formats are not supported for code-splitting builds.
Error: UMD and IIFE output formats are not supported for code-splitting builds.
    at error (/Users/clarksell/source/that/that.us/node_modules/rollup/dist/shared/rollup.js:5210:30)
    at validateOptionsForMultiChunkOutput (/Users/clarksell/source/that/that.us/node_modules/rollup/dist/shared/rollup.js:12399:16)
    at Bundle$1.generate (/Users/clarksell/source/that/that.us/node_modules/rollup/dist/shared/rollup.js:12249:17)
    at handleGenerateWrite (/Users/clarksell/source/that/that.us/node_modules/rollup/dist/shared/rollup.js:19836:23)
    at async Promise.all (index 0)
    at Task.run (/Users/clarksell/source/that/that.us/node_modules/rollup/dist/shared/watch.js:720:32)
    at Watcher.run (/Users/clarksell/source/that/that.us/node_modules/rollup/dist/shared/watch.js:640:17)

```

I'm pretty green when it comes to rollup and the magic it provides with svelte but it appears you've recently done some work in how your generating your output. The "default" output at least as it is in their rollup template is IIFE and it appears you now might have a dynamic import where we need to add `inlineDynamicImports: true` to get past the build error.

I guess my question is. Is that the expected behavior? and/or what's the suggest path to upgrade with your component?

Thanks!
~ Clark

**Comment by henriquehbr** [comment]
Hi there @csell5! Thanks for using svelte-typewriter

Could you provide the repo you are having the problem? if that's not possible, can you tell what version you are using?

There were some big changes lately related to the project structure (which you can check on #18), that included support for ESM and UMD compatible bundles for non-Svelte environments

Backwards compatibility is one of the weak spots of this project that needs some focus at the moment, sorry about this inconvenient

**Comment by csell5** [comment]
No apologies, I totally understand. The repo is here: https://github.com/thatconference/that.us I'm using version 2.1.16 and I was trying to take it to 2.2.0. https://that.us is the website.

I did see #18 and in fact I came here looking to see what I was doing wrong then figured, better to just ask and see what's up.

**Comment by henriquehbr** [comment]
I tried to reproduce the issue on [that.us repo](https://github.com/thatconference/that.us), and for now, i can confirm that setting `inlineDynamicImports` to `true` on rollup config is one of the viable solutions, otherwise, changing the `output.format` to `esm` or something else other than `iife` or `umd` also manages to solve the problem

I will document it as soon as possible to avoid others to run into the same issue as well, in case you have any suggestion of some way of applying a more solid measure to warn the end-user about this rollup behavior, feel free to express your ideas

Thanks for reporting this bug!

**Comment by csell5** [comment]
I wish I knew a bit more about rollup to be of some use. I just don't know what changing any of that does and given the Svelte team has set a default and Richard also authored Rollup I'd hate to see people not use your package cause it breaks the default. Not saying you should, just something to consider.

As for documentation. honestly I'd add some console logging postinstall on your npm package. The biggest time suck was trying to figure out what package ( and I have a lot ) was now breaking. If you dropped some message in the terminal about these changes and pointed a user back to some docs, that would be right at the time when people get it, vs having to hunt for it.

Thank you for looking into things.. 

Keep up the great work.

**Comment by henriquehbr** [comment]
Basically, what `inlineDynamicImports` does, accordingly to Rollup documentation is:

>This will inline dynamic imports instead of creating new chunks to create a single bundle. Only possible if a single input is provided.

In simple words, Rollup automatically generate a new chunk (js file separated from bundle) for each dynamic import it finds, and this chunk is only used when needed, otherwise, without this, their whole content would be dumped on the bundle (this also applies for chunks that wouldn't be used), removing all the benefits of code-splitting, and unnecessarily increasing bundle size

I'm not exactly sure why `iife` is the default output format for [the default svelte template](https://github.com/sveltejs/template), maybe for compatibility reasons, as ES modules are a new thing in the browser

But that doesn't mean the default is the only viable way, i see the official template more as a way for beginners to get started in Svelte, you could use `esm` on output format as well to get rid of this problem, or make modifications on Rollup config that suits your needs

Thank you for the suggestions! i'm going to look a bit further on this topic in order to reach the ideal solution

**Comment by TheArctesian** [comment]
Hey I just got the same error did you find a fix

**Comment by henriquehbr** [comment]
@TheArctesian you can find the solution on the [FAQs](https://github.com/henriquehbr/svelte-typewriter#faqs)

> #### UMD and IIFE output formats are not supported for code-splitting builds.
> From version 2.1.17 onwards, this library makes use of dynamic imports, if your Rollup configuration `output.format` is set to `iife` or `umd`, consider setting `inlineDynamicImports` to `true`, otherwise, change `output.format` to something else, like `esm` (for more details, consider checking #21)

**Comment by TheArctesian** [comment]
Worked thanks, going to leave this hear for the other noobs 
![image](https://user-images.githubusercontent.com/87273292/141777806-5c0d640a-07ba-4561-b222-66e8cb420c86.png)

**Comment by dragos199993** [comment]
But the above answer is not suitable for anyone. The expected behavior should be: When we import a dynamic module, to build a new chunk based on that. `inlineDynamicImports` all it does it makes a reference to the imported module, in the place it was built. 

So basically if I import dynamically  a module called `x`, I would exepct in the dist of the app it was used, to have `x.es.js` or something like that. Everytime I modify vite.config.js, seems like the `output.format` is ignored and the error still contains `umd` :cry:

**Comment by henriquehbr** [comment]
If i recall correctly, Vite works with code-splitting just fine, without the need of any additional configuration, this solution was originally aimed to rollup users, hence why it might not be suitable for your use case

You can check the [example](https://github.com/henriquehbr/svelte-typewriter/tree/main/example) project on this repo for a reference on how to work with code-splitting, by running the `build` script on `package.json` and checking the output on `dist/assets`, you can see that each module has it's own file, as you mentioned

If the error persists, could you consider sharing a reproduction of your issue? (it can be a repo, or even a separated branch on a existing one) this way i can further help with the resolution of this problem
