### ISSUE TITLE
cascade starting contents sequentially

### ISSUE THREAD

**Issue by evdama** [henriquehbr/svelte-typewriter#25]
In my app I've noticed that a `<Typewriter>` component containing two or more divs with `cascade` set on it doesn't start the div contents one after the other (sequential) but in parallel i.e. not using cascade behavior but rather default behavior.

Here's a repl that shows this behavior https://svelte.dev/repl/5698397692c54c2bb5fd03f5ea6ca8cc?version=3.31.0

**Comment by henriquehbr** [comment]
Greetings @evdama!

Many thanks for the bug report! just checked your repl, and i'll be working towards fixing it as soon as possible, i'm not sure, but looks like it will require a extensive rewrite on some of the `utils` modules due to how the DOM elements are treated by the [`getElements`](https://github.com/henriquehbr/svelte-typewriter/blob/798ff61ca834125a69b2dbd36fac853ae9e09d7a/src/utils.js#L64) function

**Comment by henriquehbr** [comment]
This problem has been fixed and released as part of [`2.4.2`](https://github.com/henriquehbr/svelte-typewriter/blob/main/CHANGELOG.md#v242), thank you so much for your contribution!

**Comment by evdama** [comment]
I can confirm, it's fixed. Thank you so much for you time and effort you put into this package, it's amazing and I use it a lot! 👍 😃
