### ISSUE TITLE
loop not working 'in-place' but stacking contents on top of each other

### ISSUE THREAD

**Issue by evdama** [henriquehbr/svelte-typewriter#28]
I've found another thingy I guess: https://svelte.dev/repl/5698397692c54c2bb5fd03f5ea6ca8cc?version=3.31.0

```js
<script>
  import Typewriter from 'svelte-typewriter'
  import { fly } from 'svelte/transition'
</script>

<Typewriter loop delay={ 5000 } interval={ 60 }>
  <div in:fly|local="{{ x: 400, delay:3000, duration: 2000 }}">
    <div>first...</div>
    <div>second...</div>
    <div>third...</div>
  </div>
</Typewriter>
```

What can be seen in the repl is that even with `loop` applied, the contents of the other `div` are stacked on top of each other rather than shown in-place i.e. in one line but sequentially after one another.

**Comment by evdama** [comment]
I just noticed that `fly` doesn't have anything to do with this issue/bug... it even shows if you just use pure html with DOM nodes deeper than one level:

```js
<script>
  import Typewriter from 'svelte-typewriter'
</script>

<Typewriter loop delay={ 5000 } interval={ 60 }>
  <div>
    <div>first...</div>
    <div>second...</div>
    <div>third...</div>
  </div>
</Typewriter>
```

**Comment by henriquehbr** [comment]
By default, elements like `<div>` and `<p>` are have `display: block`, it means that in this scenario, this element will occupy an entire row, unlike other inline elements like `<span>` whom can be put in a horizontal orientation, you can override this default behavior by modifying the `display` css property on the elements you want to be side-by-side

I hope this repl can explain this concept better: https://svelte.dev/repl/f7dc8308d3e24341a9c034e9d8bb5e47

<hr>

Besides that, in it's actual state, `loop` mode works by only getting the elements that are on the root level of the `<Typewriter>` component, so if you where to remove the parent `<div>` containing the other three divs, it would work as a charm, example below:

```svelte
<Typewriter loop delay={5000} interval={60}>
  <div>first...</div>
  <p>second...</p>
  <div>third...</div>
</Typewriter>
```

My apologies for not explicitly specifying this on the documentation, i will work towards adding more information about the different behaviors specific to each mode, this small detail can be really misleading if you are unaware of this condition

**Comment by henriquehbr** [comment]
But, your issue really made me think about refactoring how `loop` mode works, instead of getting only the elements at root level, i could thought at the following flow:

1. The `getElements` function iterates through all child elements of the `<Typewriter>` component

2. The iterator function looks for elements that contains at least one text node (non-elements) as their content ([`hasSingleTextNode`](https://github.com/henriquehbr/svelte-typewriter/blob/bdc50d14607b8fd9bdf970a979e078e5e5d628a1/src/utils.js#L32))

3. If the child fits the condition above, it is stored in an object with the following structure

```typescript
interface ChildElementData {
  childInsideParents: HTMLElement
  childToWriteText: HTMLElement
  text: string
}
```

4. After all elements were obtained, all child elements are removed from the DOM before the animation starts

5. An iteration is executed on the object where the child elements were stored (structured as `ChildElementData[]`), at first, the `childInsideParents` property is appended on the DOM

6. After that, the `text` is animated inside `childToWriteText`

7. After the `text` is fully written, it is erased, just like the normal typewriter animation, but backwards

8. After the animation is fully finished on a individual element, the `childInsideParents` element is removed from the DOM, and the cycle goes on...

Any feedback from you would be immensely appreciated, if you think it's over-engineered or rather if it would be a good idea :)

> Also, by tinkering with your repl, i just noticed that the `cascade` mode is lacking a cursor animation, i'm going to open a new issue to patch this :grin:

**Comment by evdama** [comment]
> > Also, by tinkering with your repl, i just noticed that the `cascade` mode is lacking a cursor animation, i'm going to open a new issue to patch this 😁

Indeed, I just noticed that too... probably the low hanging fruit compared to 1-8 from above about which I'm unsure at this point in time... I guess it depends a lot on the use case at hand.

In my case the root `div` is a `in:fly` containing the child divs that should then be looped once the `in:fly` has finished. I can time the start of the `<Typewriter>` simply by using its `delay` which is >= than what the `duration` of the `in:fly` is.

Having that said, I'm have no qualifying answer for your points 1-8 atm as I haven't thought about this in detail yet but really I've just been tinkering with my 3-5 use cases of `<Typewriter>` in my app. Those are roughly it's a few `default`, one `scramble`, a ton of `cascade` and a few `loop` cases 😆

**Comment by henriquehbr** [comment]
Have you tried wrapping the `<Typewriter>` component with a `<div>` containing the `in:fly` attribute? i'm not used to Svelte animations but maybe this could work

**Comment by evdama** [comment]
> Have you tried wrapping the `<Typewriter>` component with a `<div>` containing the `in:fly` attribute? i'm not used to Svelte animations but maybe this could work

yes, that's exactly what I did now... so the divs on the child level are now all on the root level and the Typewriter loop works as expected 😃

**Comment by henriquehbr** [comment]
Taking into consideration the wide range of possible use cases, the actual behavior of `loop` mode seems to be more suited for most scenarios, while making a comparison between both, i just noticed another inconsistency on the behavior of the `loop`, element attributes are not kept when they are recreated inside the `<Typewriter>`, but fortunately, this is fairly easy to fix, alongside with the missing cursor animation on the `cascade` mode

I'm going to close this issue as it's solved for now, thanks for your huge help and valuable feedback!
