### ISSUE TITLE
Flickering layout because of typewriter animation

### ISSUE THREAD

**Issue by OrangeUtan** [henriquehbr/svelte-typewriter#81]
In the first frame of the animation, the text element collapses, because there is no text in it. This causes other elements to flicker.
Wrapping the element "fixes" the problem.

[REPL](https://svelte.dev/repl/01eb82c8c16e431a86f75b4adf3744ad?version=3.49.0)

It would be nice if there was an option so that the text elements keep their size even if there is no text in them.
The wrapping method is very janky.

**Comment by henriquehbr** [comment]
This one seems fairly easy to accomplish, at first i just didn't bothered implementing such thing because i couldn't think for a use-case for it, but looking at the REPL you provided, for some scenarios it would really make sense to have something like this, thanks for bringing that up!

We can add a new boolean prop `fillSpace` (or something else, i couldn't think of a better name) that will determine whether the typewriter container element should keep occupying it's bounds even when not visible, under the hood, this would basically toggle between `visibility: hidden` and `display: none` whether we want the animation element to collapse or not

I'll work on it and let you know once it's available

**Comment by henriquehbr** [comment]
In the meantime, while we don't have an official solution for that, i managed to get a slightly cleaner workaround for your problem, which prevents the element height from appearing slightly taller than it's text:

```svelte
<script>
    import Typewriter, { concurrent } from 'svelte-typewriter';
    import { onMount } from 'svelte';
	
    let number = 0;
    let clientHeight;

    $: text = `I'm a text ${number}`;
	
    onMount(() => {
        setInterval(() => number++, 1000)
    })
</script>

<p>Text above</p>

<div style:min-height={`${clientHeight}px`} bind:clientHeight>
    <Typewriter cursor={false} interval={20} delay={100}>
        <p>{text}</p>
    </Typewriter>
</div>

<p>Text below</p>

<style>
    p {
        margin: 0;
    }
</style>
```

Here's a REPL for the snippet above: https://svelte.dev/repl/c5c661e87e264757ba2952a86886eddd?version=3.49.0

It basically gets the wrapper `div` height through binding to the `clientHeight` property, and sets the min-height accordingly

**Comment by henriquehbr** [comment]
In the case of this REPL, you should move the wrapper to be the parent of `<SplashText>` on `App.svelte`, most probably because of the problem you mentioned, that is the `clientHeight` not being calculated at the time of the rerender, so putting it outside of the component prevents that

_Note that i'm not 100% sure of the reason for this behavior as my pretty rusty when it comes to Svelte_

[REPL](https://svelte.dev/repl/dc459615e4604d23895108b7e1601cc9?version=3.49.0)

**Comment by henriquehbr** [comment]
As the project is migrating to sourcehut, i'll be closing this issue, if you feel that the reported problem haven't been solved, feel free to reopen it [here](https://todo.sr.ht/~henriquehbr/svelte-typewriter), otherwise, you can just ignore this message
